add_library(Reweighting 
	SimulationData.cpp
	SimulationDataContainer.cpp
)
#target_link_libraries(Reweighting dataAnalysisUtilities)

#This is to copy a file to the build directory
configure_file(simulationDataContainer.configfile simulationDataContainer.configfile COPYONLY)
configure_file(input_test_file_1 input_test_file_1 COPYONLY)
configure_file(input_test_file_2 input_test_file_2 COPYONLY)
configure_file(input_test_file_3 input_test_file_3 COPYONLY)
configure_file(wrong_configfile_1 wrong_configfile_1 COPYONLY)
configure_file(wrong_configfile_2 wrong_configfile_2 COPYONLY)
configure_file(wrong_configfile_3 wrong_configfile_3 COPYONLY)

#add_unit_test(SimulationData SimulationData_test dataAnalysisUtilities)
add_unit_test(SimulationDataContainer SimulationDataContainer_test Reweighting dataAnalysisUtilities)
